void set(TMaquinaVirtual *mv, int valor);
int get(TMaquinaVirtual *mv, char selec_operando);
void cc(TMaquinaVirtual *mv, int num);
int shr(int num, int bits);
void carga_programa(TMaquinaVirtual *mv, char nom_archivo[]);
void log_a_fis(TMaquinaVirtual *mv, int dir_logica, unsigned int tam_acceso, unsigned short int* dir_fisica);
void lee_memoria(TMaquinaVirtual *mv);
void escribe_memoria(TMaquinaVirtual *mv);
void carga_LAR_MAR(TMaquinaVirtual *mv, int dir_logica, unsigned int tam_acceso);
void sys_1(TMaquinaVirtual *mv);
void sys_2(TMaquinaVirtual *mv);
void imprime_binario(int);
int lee_binario();

void mov(TMaquinaVirtual *mv);
void add(TMaquinaVirtual *mv);
void sub(TMaquinaVirtual *mv);
void mul(TMaquinaVirtual *mv);
void div_mv(TMaquinaVirtual *mv);
void cmp(TMaquinaVirtual *mv);
void shl(TMaquinaVirtual *mv);
void shr_mv(TMaquinaVirtual *mv);
void sar(TMaquinaVirtual *mv);
void and(TMaquinaVirtual *mv);
void or(TMaquinaVirtual *mv);
void xor(TMaquinaVirtual *mv);
void swap(TMaquinaVirtual *mv);
void ldl(TMaquinaVirtual *mv);
void ldh(TMaquinaVirtual *mv);
void rnd(TMaquinaVirtual *mv);
void sys(TMaquinaVirtual *mv);
void jmp(TMaquinaVirtual *mv);
void jz(TMaquinaVirtual *mv);
void jp(TMaquinaVirtual *mv);
void jn_mv(TMaquinaVirtual *mv);
void jnz(TMaquinaVirtual *mv);
void jnp(TMaquinaVirtual *mv);
void jnn(TMaquinaVirtual *mv);
void not(TMaquinaVirtual *mv);
void stop(TMaquinaVirtual *mv);
